import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#000",
        justifyContent: "center",
        alignItems: "center",
    },
    backButton: {
        position: "absolute",
        top: 30,
        left: 20,
        zIndex: 1,
        backgroundColor: '#212121',
        height: 45,
        width: 45,
        borderRadius: 999,
        justifyContent: 'center',
        alignItems: 'center'
    },
    content: {
        alignItems: "center",
        paddingHorizontal: 20,
        marginTop: 40,
    },
    image: {
        width: 250,
        height: 250,
        borderRadius: 10,
        marginBottom: 10
    },
    title: {
        fontSize: 22,
        color: "#FFF",
        fontWeight: "bold",
        textAlign: "left",
    },
    author: {
        fontSize: 18,
        color: "#CCC",
        marginTop: 5,
        textAlign: "left",
    },
    containerBtns: {
        gap: 15,
    },
    sliderContainer: {
        width: "90%",
        marginTop: 20,
        flexDirection: 'row',
    },
    slider: {
        flex: 1,
    },
    timeText: {
        color: "#FFF",
        textAlign: "center",
        fontSize: 18,
    },
    playButton: {
        marginTop: 20,
        backgroundColor: '#212121',
        height: 70,
        width: 70,
        borderRadius: 999,
        marginTop: 30,
        marginBottom: -40,
        justifyContent: 'center',
        alignItems: 'center',
    },
    playlistThumbnail: {
        width: 40,
        height: 40,
        borderRadius: 5,
        backgroundColor: '#AAA',
    },
    btnListMusics: {
        position: 'absolute',
        right: 20,
        bottom: 5
    },
    bottomSheet: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: "#333",
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        zIndex: 999,
    },
    close: {
        position: 'absolute',
        top: 10,
        right: 10,
    },
    bottomSheetText: {
        color: "#FFF",
        fontSize: 20,
        marginTop: 16,
        marginBottom: 20,
        textAlign: 'center',
        marginLeft: 60,
        marginRight: 60,
    },
    playlistItem: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#595959',
        flex: 1,
        marginBottom: 20,
        borderRadius: 999,
        width: "95%",
        marginLeft: 10,
        padding: 5,
    },
    playlistName: {
        fontSize: 18,
        color: '#FFF',
        textAlign: 'center'
    },
    addButton: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 5,
    },
    addButtonText: {
        fontSize: 16,
        color: '#FFF',
    },
    messageContainer: {
        flexDirection: "row",
        alignItems: "center",
        padding: 10,
        marginBottom: 5,
    },
    userPhoto: {
        width: 40,
        height: 40,
        borderRadius: 20,
        marginRight: 10,
    },
    messageBox: {
        backgroundColor: "#444",
        padding: 10,
        borderRadius: 8,
        maxWidth: "80%",
    },
    senderName: {
        color: "#FFF",
        fontWeight: "bold",
        fontSize: 14,
    },
    messageText: {
        color: "#FFF",
        fontSize: 16,
    },
    sendMessageContainer: {
        flexDirection: 'row',
        width: '100%',
        paddingHorizontal: 10,
        marginBottom: 10,
    },
    input: {
        height: 45,
        borderColor: "#555",
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 10,
        color: "#FFF",
        backgroundColor: "#333",
        flex: 1,
    },
    sendButton: {
        marginLeft: 10,
        padding: 10,
        backgroundColor: '#444',
        borderRadius: 8,
    },
    closeModal: {
        position: 'absolute',
        top: 10,
        right: 10,
        zIndex: 999999,
    },
    modalBackground: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center'
    },
    modal: {
        flex: 1,
        zIndex: 999999,
        backgroundColor: '#ccc',
        padding: 15,
        width: '100%',
    },
    modalContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    modalContent: {
        position: 'absolute',
        bottom: 0,
        width: '100%',
        height: '60%',
        backgroundColor: "#212121",
        padding: 20,
        borderTopRightRadius: 20,
        borderTopLeftRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    friendItem: {
        flexDirection: "row",
        alignItems: "center",
        marginVertical: 5,
    },
    containerItems: {
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        paddingVertical: 5,
    },
    friendImage: {
        width: 60,
        height: 60,
        borderRadius: 9999,
        marginRight: 10,
    },
    friendName: {
        color: '#FFF',
        textShadowColor: '#000',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 2,
    },
    closeButtonText: {
        position: 'absolute',
        top: 10,
        right: 10,
        zIndex: 9999,
    },
    modalSettings: {
        position: 'absolute',
        top: 20,
        right: 10,
        zIndex: 999999,
        overflow: 'hidden',
        backgroundColor: 'rgba(27, 27, 27, 0.2)',
        borderRadius: 20,
        borderRadius: 15,
        padding: 15,
    },
    modalThumbnail: {
        height: 90,
        width: 90,
        borderRadius: 15
    },
});