import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1C1D22',
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    flexDirection: 'row',
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 10,
    paddingRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#606467',
  },
  headerFriendInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  friendPhoto: {
    width: 45,
    height: 45,
    borderRadius: 9999,
    marginLeft: 15,
    marginRight: 10,
  },
  friendUsername: {
    fontSize: 18,
    color: '#FFF',
  },
  headerIcon: {
    backgroundColor: "#313B44",
    padding: 5,
    borderRadius: 999,
  },
  btnBack: {
    width: 45,
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
  },
  flatList: {
    paddingTop: 5,
    paddingBottom: 20,
    flex: 1,
    backgroundColor: '#FFF',
    width: '100%',
  },
  mensages: {
    marginLeft: 5,
    alignItems: 'flex-end',
    flexDirection: 'row',
    flex: 1,
  },
  messagesCurrentUser: {
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
    paddingBottom: 10,
    marginBottom: 10,
    marginLeft: '20%',
    marginRight: 10,
    borderRadius: 15,
    backgroundColor: 'skyblue',
    alignItems: 'flex-end',
  },
  friendMessages: {
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
    paddingBottom: 10,
    marginBottom: 10,
    justifyContent: 'flex-end',
    marginRight: '20%',
    marginLeft: 10,
    borderRadius: 15,
    backgroundColor: '#ccc',
  },
  friendPhotoMessage: {
    width: 35,
    height: 35,
    borderRadius: 999,
    marginBottom: 20,
  },
  footer: {
    width: '100%',
    flexDirection: 'row',
    paddingTop: 3,
    paddingBottom: 3,
    paddingLeft: 10,
    paddingRight: 10,
    alignItems: 'center',
    backgroundColor: '#1C1D22',
  },
  input: {
    backgroundColor: "#313B44",
    borderRadius: 10,
    paddingLeft: 15,
    paddingRight: 15,
    height: 55,
    flex: 1,
    marginRight: 10,
    fontSize: 18,
    color: '#FFF',
    marginLeft: 10,
  },
  btnSendMensage: {
    backgroundColor: '#313B44',
    padding: 10,
    borderRadius: 999,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalPhoto: {
    width: 350,
    height: 350,
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
  playVideo: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    height: 50,
    width: 50,
    borderRadius: 999,
    backgroundColor: '#212121',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 3,
  },
  videoContainer: {
    width: "100%",
    height: '100vh',
    backgroundColor: "#000",
    borderRadius: 10,
    overflow: "hidden",
  },
  video: {
    width: "100%",
    height: "100%",
  },
  closeButton: {
    position: "absolute",
    top: 10,
    right: 10,
  },
  controls: {
    position: "absolute",
    bottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    width: "80%",
    paddingHorizontal: 20,
  },
  controlButton: {
    padding: 10,
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.8)",
  },
  pressable: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  }
});
