import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1C1D22',
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    flexDirection: 'row',
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 10,
    paddingRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#606467',
  },
  headerFriendInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  friendPhoto: {
    width: 45,
    height: 45,
    borderRadius: 9999,
    marginLeft: 15,
    marginRight: 10,
  },
  friendUsername: {
    textAlign: 'center',
    color: '#FFF',
    textAlign: 'center',
    fontSize: 20,
    width: '100%',
  },
  headerIcon: {
    backgroundColor: "#313B44",
    padding: 5,
    borderRadius: 999,
  },
  btnBack: {
    width: 45,
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
  },
  flatList: {
    paddingHorizontal: 20,
    width: '100%',
  },
  playlistContainer: {
    backgroundColor: '#606467',
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 10,
    width: '100%',
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 20,
  },
  line: {
    borderWidth: 2,
    borderColor: '#AAA',
    borderRadius: 9999,
    marginTop: 10,
  },
  numSongs: {
    color: '#d1d1d1',
    fontSize: 16,
    position: 'absolute',
    top: 7,
    right: 17,
  },
  playlistImage: {
    width: 100,
    height: 100,
    borderRadius: 20,
    marginRight: 10,
  },
  playlistName: {
    color: "#fff",
    fontSize: 18,
    width: '60%',
    marginLeft: 10,
  },
  titleSongPreview: {
    color: '#AAA',
    width: '67%',
    marginLeft: 3,
  },
  footer: {
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    backgroundColor: "#1e1e1e",
  },
  input: {
    backgroundColor: "#313B44",
    borderRadius: 10,
    paddingLeft: 15,
    paddingRight: 15,
    height: 55,
    flex: 1,
    marginRight: 10,
    fontSize: 18,
    color: '#FFF',
    marginLeft: 10,
  },
  addButton: {
    marginLeft: 10,
    backgroundColor: "#1DB954",
    padding: 10,
    borderRadius: 5,
  },
  imagePicker: {
    marginRight: 10,
    backgroundColor: "#555",
    padding: 10,
    borderRadius: 5,
  },
});
